spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.138.128/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.138.128
    port: 6379
server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wx3a1c7193b652c1db
  mpAppSecret: e38a8e914c2efa668fb3906fce3cb7f7
  openAppId:
  openAppSecret:
  mchId:
  mchKey:
  KeyPath:
  notifyUrl: http://yjlhz.nat300.top/sell/pay/notify

projecturl:
  wechatMpAuthorize: http://yjlhz.nat300.top
  wechatOpenAuthorize: http://yjlhz.nat300.top
  sell: http://yjlhz.nat300.top
